### PR TITLE
Fixed some issues VAT patterns

### PR DESCRIPTION
**Pull request by madlep**
This PR includes fixes to various VAT code patterns. We spotted these as we use a number of VAT validation systems on [Envato Elements](https://elements.envato.com/) and tested differences between them (vatcode-validator for front end, [valvat](https://github.com/yolk/valvat) for backend, and another in-house library in a separate system data gets sent to)
- added `BG` codes
- `FR` codes shouldn't allow `O` or `I` characters
- `GBGD` codes should only allow `0` to `499`
- `GBHA` codes should only allow `500` to `999`
- `RO` codes can be 2-10 digits

misc other changes
- reorder patterns to be alphabetical so they're easier to audit manually
- added positive and negative test cases for patterns that have changed
- test failures are output in red so they're easier to see
- test process has status code of `1` on failures (and still status of `0` on success)

### CODE REVIEW

**Comment by elliotblackburn** [comment]
Thanks so much for the contribution, it's been a long time since I've looked at this module so I'm not surprised there are some problems with it. Great spot on the issues and thanks for contributing the changes back!

I'm just going through the changes now to double check the changes and make sure they're all correct. If all is well then I'll merge and do a re-release of the module in npm as soon as possible. I'd hate for people to be getting false validation.

**Comment by elliotblackburn** [comment]
Everything seems to look good. I'm going to get another version out in the next few hours on NPM with these changes. Thanks for the contribution @madlep!

**Comment by madlep** [comment]
Awesome. Thanks for the library and for the quick turnaround @BlueHatbRit 😄

**Comment by elliotblackburn** [comment]
No worries, I wrote this when I had no idea what I was doing so I'm glad someones made a few corrections. I'll see about moving the tests into a proper test running and adding travis over the next few days just to make it a little more reliable and trustworthy for anyone using it.

1.0.3 is up now on npm so you should be able to update any of your projects using the old version.

Have a great day @madlep!

**Pull request merged**
