### PR TITLE
Fix prefix typo, Portugal not validating

### PR DESCRIPTION
**Pull request by gbakernet**

### CODE REVIEW

**Comment by elliotblackburn** [comment]
I've been holiday this week, sorry for the delay! I'll check it over now and look to merge and release if all is well in a few hours :)

**Comment by elliotblackburn** [comment]
All is looking good, thanks for identifying that one. I'll do a re-release over the next few hours to make sure this is sorted on NPM!

Thanks so much for the contribution!

**Comment by elliotblackburn** [comment]
Made a re-release under 1.0.4 with this fix. Thanks for the contribution again @gbakernet

**Comment by gbakernet** [comment]
No worries. Thanks for the merge.

**Pull request merged**
